function :
  _target_  : compose.compose
  _args_    :
      - ${eval:'lambda x,u:u*(x-x**3)+(1-u)*(-x)'}

IC_distribution:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Normal
    loc       : 0
    scale     : 2
  dim : ${..dim}

external_input_distribution:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_: torch.distributions.Uniform
    low     : 0
    high    : 1
  dim : ${..external_input_dim}

dist_requires_dim : false
has_external_input : true

name : bifurcating_bistable1D

dim  : 1
external_input_dim  : 1

lims :
  x : [-2,2]
  y : [0,1]

equation_latex  : x-x^3
analytical_eigenfunction:
  _target_  : compose.compose
  _args_    :
    - ${eval:'lambda x: x[...,0:1]/((1-x[...,0:1]**2)**2)**0.5 * (-x[...,1:2])'}
#    - - ${eval:'lambda x:x/((x**2-1)**2)**0.25'}