function :
  _target_  : compose.compose
  _args_    :
    - _target_  : torch.stack
      _partial_ : true
      dim       : -1
    - ${eval:'lambda x:(x[...,0]-x[...,0]**3, -x[...,1])'}
IC_distribution:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Normal
    loc       : 0
    scale     : 2
  dim : ${..dim}

dist_requires_dim : false
name            : bistable2D
dim  : 2
equation_latex  : x-x^3
analytical_eigenfunction:
  _target_: compose.compose
  _args_:
    - ${eval:'lambda x,y:x/((x**2-1)**2)**0.25'}
