function  :
  _target_  : dynamical_functions.change_speed
  func    : ${..original_function}
  factor  : 13.003 #1/Re(lambda) where lambda is the unstable eigenvalue of the saddle point

original_function :
  _target_  : ssr_module.steady_state_reduction_example_torch.get_ssr_dynamics_function
  device    : cpu
run_traj : true

IC_distribution_fit:
  _target_  : utils.list_concat
  _args_:
#    - ${...isotropic_gaussians}
    - ${...iid_betas}
    - ${...IC_distribution_uniform_list}

isotropic_gaussians:
  _target_  : custom_distributions.isotropic_gaussians
  mean      : ${..point_on_separatrix}
  scales    : ${..scale_range}

iid_betas:
  _target_  : custom_distributions.list_of_iid_betas
#  mean      : ${..point_on_separatrix}
  mean      : ${..saddle_point}
  scales    : ${..scale_range}

scale_range :
  _target_  : numpy.array
  object  : [5e-3,1e-2,5e-2,0.1] #0.2

IC_distribution_uniform_list:
  - ${..IC_distribution_uniform}

IC_distribution_uniform:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Uniform
    low       : 0.0
    high      : 1.0
  dim : ${..dim}


IC_distribution  :
#  _target_  : rnn.hidden_distribution_from_model
#  model     : ${..loaded_RNN_model}
#  dataset   : ${..RNN_dataset}
  _target_  : torch.distributions.MultivariateNormal
  loc  :
    _target_ : torch.zeros
    size     : ${eval:'(${...dim},)'}
  covariance_matrix:
    _target_  : torch.eye
    n  : ${...dim}
dist_requires_dim : false

loaded_RNN_model:
  _target_: rnn.set_model_with_checkpoint
  model: ${..RNN_model}
  checkpoint:
    _target_: torch.load
    f: ${savepath}/RNNmodel.torch
    weights_only: true

RNN_model:
  _target_  : rnn.GRU_RNN
  ob_size   : ${..k_bit}
  act_size  : ${..k_bit}
  num_h     : ${..dim}

dim  : 2

lims  :
  x : [0.0,1.0]
  y : [0.0,1.0]


attractors:
  _target_  : ssr_module.steady_state_reduction_example_torch.get_attractors_ssr
  device    : cpu

point_on_separatrix :
  _target_          : separatrix_point_finder.find_separatrix_point_along_line
  dynamics_function : ${..function}
  attractors        : ${..attractors}
  external_input    : null
  num_iterations    : 2
  num_points        : 20
  final_time        : 20 #200

saddle_point  :
  _target_  : separatrix_point_finder.find_saddle_point
  dynamics_function : ${..function}
  point_on_separatrix : ${..point_on_separatrix}
  T : 1
  steps : 100

plot_fixed_points:
  - x : null
    y : null
    marker  : o
    label   : stable fixed point
    s       : 50
    zorder  : 2
  - x : null
    y : null
    marker  : x
    label   : unstable fixed point
    s       : 100
    linewidths : 1.5
    zorder  : 2



name  : microbiome_SSR_GLV_${.dim}D