defaults:
  - main
  - _self_


train_KEF_model   : false
save_KEF_model    : false
load_KEF_model    : true
run_analysis      : true

dynamics_choice : 1bitflipflop_Vanilla64D_long_isotropic

device  : cuda:0

separatrix_locator :
  num_models  : 1

separatrix_locator_fit_kwargs:
  num_epochs: 1000
  # num_epochs: 10     # switch to this later
  batch_size: 1000      # use this for now
#  batch_size: 5000     # better alternative?
  balance_loss_lambda : 5e-2
  RHS_function: 'lambda psi: psi-psi**3'