_target_: utils.setattrs_kwargs
target:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torch.nn.Linear
      in_features: ${....input_size}
      out_features: ${....hidden_size}
    - _target_: architectures.ResidualBlock
      hidden_dim: ${....hidden_size}
    - _target_: architectures.ResidualBlock
      hidden_dim: ${....hidden_size}
    - _target_: architectures.ResidualBlock
      hidden_dim: ${....hidden_size}
    - _target_: architectures.ResidualBlock
      hidden_dim: ${....hidden_size}
    - _target_: architectures.ResidualBlock
      hidden_dim: ${....hidden_size}
#    - _target_: torch.nn.Linear
#      in_features: ${....hidden_size}
#      out_features: ${....output_size}
    - _target_: torch.nn.Linear
      in_features: ${....hidden_size}
      out_features: 2
    - _target_: learn_koopman_eig.partialised_RBF_maker
      in_features_dim: 2
      num_kernels: 100 #00
      out_features_dim: 1
      normalization: false
      reset_params:
        upper_bound_kernels: 2
        std_shapes: 3

input_size: ${dynamics.dim}
hidden_size: 100
output_size: 1
num_layers: 6
name: RBFResidualMLP_layers${.num_layers}_hidden${.hidden_size}_output${.output_size}
