function  :
  _target_  : dynamical_functions.change_speed
  func    : ${..original_function}
  factor  : 10 #20 #71.25 #1 #13.003 #1/Re(lambda) where lambda is the unstable eigenvalue of the saddle point

original_function :
  _target_  : ssr_module.steady_state_reduction_example_torch.get_dynamics_function
  device    : cpu
run_traj : true

IC_distribution_fit:
  _target_  : utils.list_concat
  _args_:
#    - ${...IC_distribution_list}
    - ${...iid_gammas}
#    - ${...cubic_hermite_distribution_list}
#    - ${...isotropic_gaussians}
#    - ${...iid_betas}
#    - ${...IC_distribution_uniform_list}

isotropic_gaussians:
  _target_  : custom_distributions.isotropic_gaussians
  mean      : ${..point_on_separatrix}
  scales    : ${..scale_range}

iid_gammas:
  _target_  : custom_distributions.list_of_iid_gammas
#  mode      : ${..point_on_separatrix}
  mode      : ${..saddle_point}
#  scales    : ${..scale_range}
  scales    : ${..position_wise_scale_range}

iid_betas:
  _target_  : custom_distributions.list_of_iid_betas
  mean      : ${..point_on_separatrix}
  scales    : ${..scale_range}

scale_range :
  _target_  : numpy.array
#  object  : [1e-2,0.1,0.3,0.5,0.8,1.0]
  object  : [1e-2,0.1,0.3,1.0]

# dist_weights  : [1.0,1.0,1.0,4.0]

position_wise_scale_range:
  _target_  : numpy.outer
  a         : ${..scale_range}
  b         : ${..position_wise_distances_between_attractors}

#position_wise_distances_between_attractors_eps: ${eval:${.position_wise_distances_between_attractors}+1e-4}}

position_wise_distances_between_attractors:
  _target_  : torch.abs
  input     :
    _target_  : torch.diff
    input     : ${...attractors}
    axis      : 0

IC_distribution_list:
  - ${..IC_distribution}

IC_distribution:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Exponential
    rate      : 1.0
  dim : ${..dim}

################

cubic_hermite_distribution_list:
  - _target_  : custom_distributions.CubicHermiteSampler
    x         : ${...attractors}
    scale     : 0.01
    alpha_dist  : ${...alpha_dist}

  - _target_  : custom_distributions.CubicHermiteSampler
    x         : ${...attractors}
    scale     : 1.0
    alpha_dist  : ${...alpha_dist}
  - _target_  : custom_distributions.CubicHermiteSampler
    x         : ${...attractors}
    scale     : 2.0
    alpha_dist  : ${...alpha_dist}
  - _target_  : custom_distributions.CubicHermiteSampler
    x         : ${...attractors}
    scale     : 3.0
    alpha_dist  : ${...alpha_dist}

alpha_dist  : #null
#  _target_  : torch.distributions.Beta
#  concentration1: 2
#  concentration0: 2
  _target_  : torch.distributions.Uniform
  low : 0.02
  high : 0.3

##############
#IC_distribution  : ${.IC_distribution_uniform}
dist_requires_dim : false

loaded_RNN_model:
  _target_: rnn.set_model_with_checkpoint
  model: ${..RNN_model}
  checkpoint:
    _target_: torch.load
    f: ${savepath}/RNNmodel.torch
    weights_only: true

RNN_model:
  _target_  : rnn.GRU_RNN
  ob_size   : ${..k_bit}
  act_size  : ${..k_bit}
  num_h     : ${..dim}

dim  : 11

lims  :
  x : [0.0,1.0]
  y : [0.0,1.0]


attractors_from_authors:
  _target_  : ssr_module.steady_state_reduction_example_torch.selected_attractors

random_points :
  _target_  : custom_distributions.sample
  dist      : ${..IC_distribution}
  shape     : [30,]

attractors_unclustered:
  _target_ : odeint_utils.run_odeint_to_final
  func     : ${..function}
  y0       : ${..random_points} #${..attractors_from_authors}
  T       : 1000

attractors: ${.attractors_from_authors}
#  _target_  : clustering.get_cluster_centroids
#  data      : ${..attractors_unclustered}
#  k         : 2

#
point_on_separatrix :
 _target_          : separatrix_point_finder.find_separatrix_point_along_line
 dynamics_function : ${..function}
 attractors        : ${..attractors}
 external_input    : null
 num_iterations    : 2
 num_points        : 20
 final_time        : 200
#
saddle_point:
 _target_  : separatrix_point_finder.find_saddle_point
 dynamics_function : ${..function}
 point_on_separatrix: ${..point_on_separatrix}
 T : 1

# saddle_point:
#   _target_: torch.load
#   f: ${savepath}/saddle_point.pt

# point_on_separatrix:
#   _target_: torch.load
#   f: ${savepath}/point_on_separatrix.pt

#  _target_  : separatrix_point_finder.find_saddle_point
#  dynamics_function : ${..function}
#  point_on_separatrix : ${..point_on_separatrix}
#  T : 10
#  steps : 100

plot_fixed_points:
  - x : null
    y : null
    marker  : o
    label   : stable fixed point
    s       : 50
    zorder  : 2
  - x : null
    y : null
    marker  : x
    label   : unstable fixed point
    s       : 100
    linewidths : 1.5
    zorder  : 2



#name  : microbiome_GLV_${.dim}D_point_on_separatrix
name  : microbiome_GLV_${.dim}D_saddlepoint #_weights1_1_1_4