defaults:
  - main
  - _self_

dynamics_choice : bistable1D_sin

model_choice  : ResRBF

device  : cuda:1

separatrix_locator :
  num_models  : 1

separatrix_locator_fit_kwargs:
  num_epochs: 1000
  batch_size: 1000
  balance_loss_lambda : 5e-2
  optimizer:
    lr  : 1e-3
    weight_decay: 1e-3
  RHS_function: 'lambda psi: psi-psi**3'

plot_trajectories_in_2D : true

