defaults:
  - main
  - models@model : input_centered_and_scaled_ResRBF
  # - dynamical_systems@dynamics : finkelstein_fontolan_RNN_multiscale_fim_only_anisotropic
  - _self_


train_KEF_model   : false
save_KEF_model    : false
load_KEF_model    : true
run_analysis      : true

# dynamics_choice : finkelstein_fontolan_RNN_multiscale_on_separatrix_speed40
# dynamics_choice : finkelstein_fontolan_RNN_multiscale_mixture_on_separatrix_speed40_anisotropic
# dynamics_choice : finkelstein_fontolan_RNN_multiscale_list_base_and_fim_anisotropic
dynamics_choice : finkelstein_fontolan_RNN_multiscale_fim_only_anisotropic

model:
  hidden_size : 800
  num_layers  : 25

  # hidden_size : 1200
  # num_layers  : 25

  # hidden_size : 800
  # num_layers  : 45
  num_kernels : 10
  # input_scale_factor: 0.01
  input_scale_factor: 0.02
  input_center:
    _target_: learn_koopman_eig.concat_last_dim
    _args_:
      - ${dynamics.point_on_separatrix}
      - ${dynamics.static_external_input}
  scale_last_layer_by_inv_sqrt_hidden: true

device  : cuda:2

separatrix_locator :
  num_models  : 1

separatrix_locator_fit_kwargs:
  # num_epochs: 1000
  # batch_size: 1000     

  num_epochs: 5000     # switch to this later
  batch_size: 3000
#  batch_size: 1000      # use this for now
  # num_epochs: 5000 #1000
  
  balance_loss_lambda : 5e-2
  optimizer:
    lr            : 1e-4
    weight_decay  : 1e-4 #0.0 #1e-3  #5e-3
  RHS_function: 'lambda psi: psi-psi**3'
experiment_details : experiment_${model.name}_lr${separatrix_locator_fit_kwargs.optimizer.lr}_noscheduler_l2${separatrix_locator_fit_kwargs.optimizer.weight_decay}_batch${separatrix_locator_fit_kwargs.batch_size}_epochs${separatrix_locator_fit_kwargs.num_epochs}_${separatrix_locator_fit_kwargs.normaliser._target_}_gmmratio${separatrix_locator_fit_kwargs.gmm_mix_ratio}_eigenvalue${eigenvalue}_AdamW #_balanceloss${separatrix_locator_fit_kwargs.balance_loss_lambda} 